<a href="https://colab.research.google.com/github/Meenutomar/Python/blob/main/Numpy.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [7]:
#numpy
#diff btw lists and arrays in python

#data types storage
l = [1,2,"hello"] #multiple data
print(l)

#impoting module
import numpy as np

#creating arrays
a = np.array([1,2,3])
print(a)

print("____________________________________")
#numerical operaions
a = np.array([1,2,3])
b = np.array([4,5,6])
print(a+b)
print(a-b)
print(a*b)
print(a/b)
print(a**b)
print(a%b)


print("____________________________________")
#modification

#Consumes less memory
#fast as compared to the python list
#convenient to use



[1, 2, 'hello']
[1 2 3]
____________________________________
[5 7 9]
[-3 -3 -3]
[ 4 10 18]
[0.25 0.4  0.5 ]
[  1  32 729]
[1 2 3]
____________________________________


In [8]:
%timeit [j**4 for j in range(1,9)] #for time check


2.6 µs ± 32 ns per loop (mean ± std. dev. of 7 runs, 100000 loops each)


Array


In [12]:

#how to create Array
import numpy as np
a = np.array([1,3,4,55])
print(a)

b = np.array([[1,2,3],[4,5,6]])
print(b)

[ 1  3  4 55]
[[1 2 3]
 [4 5 6]]


In [14]:
import numpy as np
x = [1,2,3,4]
y = np.array([1,2,3,4,5])
print(x)
print(type(x))
print("_____________________________________")
print(y)
print(type(y))


[1, 2, 3, 4]
<class 'list'>
_____________________________________
[1 2 3 4 5]
<class 'numpy.ndarray'>


In [17]:
l = []
for i in range (1,7):
  int_1 = int(input("enter the value: "))# get data from user
  l.append(int_1) # add in list
print(np.array(l))


enter the value: 12
enter the value: 34
enter the value: 23
enter the value: 2
enter the value: 4
enter the value: 23
[12 34 23  2  4 23]


Types of Array

1-D Array [ ]

2-D Array[[ ]]

3-D Array[[[ ] ]]

Higher D Arrays


In [2]:
import numpy as np
are2 = np.array([[1,2,3],[4,5,6]])#2d Array
print(are2)
print(are2.ndim)

[[1 2 3]
 [4 5 6]]
2


In [4]:
import numpy as np
are3 = np.array([[[1,2,3],[4,5,6],[7,8,9]]])#3d Array
print(are3)
print(are3.ndim)#array type

[[[1 2 3]
  [4 5 6]
  [7 8 9]]]
3


Create Numpy Array Using Numpy functions


In [14]:
#Array filled with O
import numpy as np
print("1-D array with 0")
a = np.zeros(4)
print(a)
print("----------------------------------------------------")
b = np.zeros((3,4))
print(b)
print("___________________________________________")
c = np.zeros((3,4,2))
print(c)
print("___________________________________________")
#Array filled with 1's
import numpy as np
a = np.ones(4)# using ones functions
print(a)
print("----------------------------------------------------")
b = np.ones((3,4))
print(b)
print("___________________________________________")
c = np.ones((3,4,2))
print(c)
print("___________________________________________")
#Array filled with range
import numpy as np
a = np.arange(4)
print(a)
print("----------------------------------------------------")
print("range")
b = np.arange(1,10)
print(b)
print("___________________________________________")
b = np.arange(1,10,2)
print(b)
print("___________________________________________")
#Array filled with random numbers
import numpy as np
a = np.random.randint(1,10,3)
print(a)
print("----------------------------------------------------")
b = np.random.randint(1,10,3)
print(b)
print("___________________________________________")
#Create an empty array
import numpy as np
a = np.empty(4)
print(a)
print("----------------------------------------------------")
b = np.empty((3,4))
print(b)
print("___________________________________________")
#Array diagonal element filled with 1's
import numpy as np
a = np.eye(3)

print(a)
print("----------------------------------------------------")
b = np.eye(3,4)
print(b)
print("___________________________________________")
#Array filled with specific value
import numpy as np
a = np.full(4,5)
print(a)
print("----------------------------------------------------")
b = np.full((3,4),5)
print(b)
print("___________________________________________")

#create an array with values that are spaced Linearly in a specified interval
ar_dia = np.linspace(0,10,num=5)
print(" spaced Linearl")
print(ar_dia)

1-D array with 0
[0. 0. 0. 0.]
----------------------------------------------------
[[0. 0. 0. 0.]
 [0. 0. 0. 0.]
 [0. 0. 0. 0.]]
___________________________________________
[[[0. 0.]
  [0. 0.]
  [0. 0.]
  [0. 0.]]

 [[0. 0.]
  [0. 0.]
  [0. 0.]
  [0. 0.]]

 [[0. 0.]
  [0. 0.]
  [0. 0.]
  [0. 0.]]]
___________________________________________
[1. 1. 1. 1.]
----------------------------------------------------
[[1. 1. 1. 1.]
 [1. 1. 1. 1.]
 [1. 1. 1. 1.]]
___________________________________________
[[[1. 1.]
  [1. 1.]
  [1. 1.]
  [1. 1.]]

 [[1. 1.]
  [1. 1.]
  [1. 1.]
  [1. 1.]]

 [[1. 1.]
  [1. 1.]
  [1. 1.]
  [1. 1.]]]
___________________________________________
[0 1 2 3]
----------------------------------------------------
range
[1 2 3 4 5 6 7 8 9]
___________________________________________
[1 3 5 7 9]
___________________________________________
[8 6 2]
----------------------------------------------------
[2 5 3]
___________________________________________
[0.0e+000 4.9e-324 9.9e-324

create numpy Arrays with random Numbers

In [16]:
#rand() the function is used to genrate 1 to 0
import numpy as np
a = np.random.rand(5)
print("1-D array")
print(a)


1-D array
[0.9731781  0.40098223 0.96581973 0.39370715 0.6776783 ]


Randn()


In [18]:
var = np.random.randn(5)# its provide - values
print(var)




[-0.4295981   1.17749014  1.1270973  -1.07827754 -0.49579186]


ranf() the functin for doing random sampling in numpy it returns an array of specified shapes and fills it with random floats in the half interval(0,0,1,0)


In [20]:
var1 = np.random.ranf(5)
print(var1)

[0.40314538 0.7454761  0.91889636 0.86886032 0.21861599]


rRandind() +,_ bpth value

In [21]:
v = np.random.randint(4,10,5) # make range
print(v)

[6 9 6 7 5]


In [23]:
v = np.random.randint(2,size=10)
print(v)

[1 0 0 1 0 1 1 1 1 0]


Data Type in Numpy

In [25]:
import numpy as np
a = np.array([1,2,3,5])
print("data type:",a.dtype)

data type: int64


In [26]:
b  = np.array([1.2,3.4,5.6])
print("data type:",b.dtype)

data type: float64


In [27]:
s = np.array(["a","b","c"])
print("data type:",s.dtype)

data type: <U1


In [28]:
x = np.array(["a","b","c"],dtype="S")
print("data type:",x.dtype)

data type: |S1


In [29]:
a = np.array([1,2,3,4],dtype="i4")
print("data type:",a.dtype) #



data type: int32


In [33]:
x2 = np.array([1.2,3.4,5.6])
new = x2.astype(int)
print(new)
print(new.dtype)



[1 3 5]
int64
